### ISSUE TITLE
i want yr help my friend

### ISSUE THREAD

**Issue by Vishwas567917** [george0st/qgate-model#156]
i want yr help in my readme profile 
do u know how to add a flag counter in readme because i add but i only see 2 country but i add 250 country i cant find the problem can u help me plz

**Comment by george0st** [comment]
Hi @Vishwas567917 , I used the code below (you have to specify only **username** and **expected style**). The counter will keep counter position from first time to use and will be increased only from the place of usage).

`![Profile views counter](https://komarev.com/ghpvc/?username=<yourname>&style=flat-square)`

I think, it is fine that you started from value 1 ... you will grow in time.

**Comment by Vishwas567917** [comment]
thanks a lot

**Comment by george0st** [comment]
I understand, but I do not have experience about that.

**Comment by Vishwas567917** [comment]
ooo ok thank but
